### ISSUE TITLE
Autodistill execution error

### ISSUE THREAD

**Issue by sa136199** [autodistill/autodistill#124]
### Search before asking

- [X] I have searched the Autodistill [issues](https://github.com/autodistill/autodistill/issues) and found no similar feature requests.

### Question

When I use Autodistill on Roboflow to label images
After the marking is completed, the marked pictures will be automatically moved from Unassigned to Dataset
But in recent days, it cannot be executed correctly
The error message is as shown below
Is there a solution or do I need to wait for the system to repair automatically?
Thanks!
![92425ee9f4190bbe335416e0f673b264a7c47b5d](https://github.com/autodistill/autodistill/assets/158792600/299b85af-fb17-468c-beb7-47cc682ca1c7)
![f52cf21e7dc59429a131f8185bc49e9011df7a71](https://github.com/autodistill/autodistill/assets/158792600/c97a1f7d-3af3-46b5-b0fa-1230ec38a307)
![590d358c5778e5a81f47b80a6f56d4c23be7850a](https://github.com/autodistill/autodistill/assets/158792600/9ce8f4ad-9540-413f-a434-76f77f199c7c)

**Comment by nguyenthekhoig7** [comment]
Hi, same here. I got the same problem, and I found a walkaround to get over it (not sure if it will work to submit as a PR).

You can open the `yolo.py` file (click on the blue link to the file), change the line that directly causing this error from 
`    for xyxy, mask, _, class_id, _ in detections:`

to

`    for xyxy, mask, _, class_id, _ , _ in detections:` (add one placeholder)

The reason for this walkaround is that when I printed out the detections variable and turned out it had 6 var instead of 5, so I added one.

Hope this helps.

**Comment by nguyenthekhoig7** [comment]
Since the file I made the change to is in the _supervision_ folder, not _autodistill_, I am not sure if I can submit a PR for this. I hope that there's another way for this rather than manually fixing like the way I did.

**Comment by sa136199** [comment]
Thank you
This method solved my problem
I also hope there can be a fundamental solution
Anyway thank you very much

**Comment by SkalskiP** [comment]
Hi @nguyenthekhoig7 and @sa136199, This problem is related to a bug in the current version of `supervision`. All you must do is `pip install supervision==0.19.0rc2` in your Python environment. This will update `supervision` and the bug should go away.

**Comment by sa136199** [comment]
Thank you for providing a more convenient solution

**Comment by capjamesg** [comment]
We will be releasing a new version of supervision in the next week that will solve this problem.

**Comment by capjamesg** [comment]
This problem has since been fixed in supervision, so I am closing this issue. Thank you!

**Comment by mir-abir-hossain** [comment]
![image](https://github.com/autodistill/autodistill/assets/78850784/48c785c5-37be-4b42-8563-45b0c0ed50c3)
I am getting the same error in kaggle notebook as of today.

**Comment by capjamesg** [comment]
@mir-abir-hossain Can you run `pip install --upgrade supervision` in your notebook and then run Autodistill again?

**Comment by mir-abir-hossain** [comment]
I did that, but still the same problem persists. I checked the version of supervision by using`pip list` and it is showing the following. ( 0.20.0 )
![image](https://github.com/autodistill/autodistill/assets/78850784/4ea38d81-1843-4377-9450-52ef7eeabc66)

This was my full code:
img = "/kaggle/input/rsud20k-bangladesh-road-scene-understanding/rsud20k/images/train/train10000.jpg"
imgg = cv2.imread(img)
results = base_model.predict(imgg)
plot(
    image=imgg,
    classes=base_model.ontology.classes(),
    detections=results
)

**Comment by dkirby-ms** [comment]
I am also seeing this same problem. @mir-abir-hossain  did you find a fix?

**Comment by mir-abir-hossain** [comment]
not yet @dkirby-ms

**Comment by dkirby-ms** [comment]
Adding the additional _ into the unpack of the detections object in utils.py:71 worked for me.
